# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsApp', '0011_orderdetails_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='totalPrice',
            field=models.FloatField(),
        ),
    ]
